### PR TITLE
Vue3 update

### PR DESCRIPTION
**Pull request by nxtedecoy**
**Summary of Changes**
Added UI prebuilt UI components to .rdvue.

**Related Issues**

**Additional Context**

**Screenshots/Videos**

**Testing Steps**

---

**Checklist**

-   [ ] Sufficient unit tests added

-   [ ] Sufficient logging added

-   [ ] Sufficient in-line code documentation

### CODE REVIEW

**Comment by Davane** [comment]
@nxtedecoy I ran it locally however, it seems only the installation of Shadcn was done. The CLI didn't add the component I selected from the list to my project.
Screenshot 2024-01-24 at 2 19 22 PM

Is that the expected behaviour or was it supposed to add the selected component to my project? @nxtedecoy

**Comment by Davane** [comment]
Is there a specific reason why the components are prefixed with `r-`. For example `r-btn`? @nxtedecoy

**Comment by Davane** [comment]
The command to add the components from the new component libraries is currently `frontier vue add component --ui`. @andre-vidal was this the expectation? 

Maybe it could be something like `frontier vue plugin shadcn --install` or `frontier vue plugin component --install`. Then we could do `frontier vue plugin [ shadcn | component ] button` to add a new component from the component library to the project. We could get rid of the install flag all together and install the dependencies (if not already installed) when we try to add a new component from the library to the project.
**The reason why I expected something along that line is because:**
1. It follows a similar pattern as Buefy.
2. It separates the creation of a custom component and a component from the library (which has pros and cons).

**Things I don't like about it:**
1. The command is a bit long
2. We would have two separate commands to add components. The original `frontier vue add component` command and this new way with the plugin keyword.

Not sure if this approach is the best route but any ideas are welcome even if that means leaving it as is with the --ui flag.  @carl-clarke @Saspect-IO @forevergareth any thoughts?

**Comment by nxtedecoy** [comment]
> Is there a specific reason why the components are prefixed with `r-`. For example `r-btn`? @nxtedecoy

Yea these were copied from the VMBS codebase and I didn't change the names so there's no reason really.

**Comment by nxtedecoy** [comment]
> @nxtedecoy I ran it locally however, it seems only the installation of Shadcn was done. The CLI didn't add the component I selected from the list to my project. Screenshot 2024-01-24 at 2 19 22 PM
> 
> Is that the expected behaviour or was it supposed to add the selected component to my project? @nxtedecoy

Yea it should've added the component to your project. Thing is the updated template isn't what gets pulled with `frontier vue create-project` command. So the components aren't actually available so what you'll have to do to test is just copy the [`.rdvue/template/components`](https://github.com/realdecoy/rdvue-template/tree/vue3-update/.rdvue/template/components) folder into your current project and it will work. I'll add that to the frontier PR as a note. My bad.

**Comment by Davane** [comment]
> Yea these were copied from the VMBS codebase and I didn't change the names so there's no reason really.


OK understood I will leave these as is for now with the intention to changing them to something else later.

**Comment by Davane** [comment]
> Yea it should've added the component to your project. Thing is the updated template isn't what gets pulled with `frontier vue create-project` command. So the components aren't actually available so what you'll have to do to test is just copy the [`.rdvue/template/components`](https://github.com/realdecoy/rdvue-template/tree/vue3-update/.rdvue/template/components) folder into your current project and it will work. I'll add that to the frontier PR as a note. My bad.

Thanks for clarifying. So that functionality will need to be added but that hasn't been fully fleshed out as yet so will approve this with the intention to update it

**Review by Davane — APPROVED** [review]

**Review by andre-vidal — APPROVED** [review]

**Pull request merged**
